version: "3.8"
services:
  mysql:
    platform: linux/x86_64 # for apple silicon
    image: mysql:8.0.23
    container_name: jwt-auth-mysql
#    hostname: mysql
    ports:
      - "3333:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=jwt-auth
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
  redis:
    image: redis:6.0-alpine
    container_name: jwt-auth-redis
#    hostname: redis
    restart: always
    ports:
      - "6340:6379"
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  mysql_data:
  mysql_config: